apiVersion: v1
kind: Service
metadata:
  name: sakai-service
  namespace: {{ .Values.namespace.name }} 
spec:
  selector:
    app: sakai-container
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer


